### ISSUE TITLE
Import STL file，How to  convert from right  to left  handed coordinates?

### ISSUE THREAD

**Issue by xonze** [karl-/pb_Stl#4]
When import STL file，How to  convert from right  to left  handed coordinates?

**Comment by karl-** [comment]
There isn't a way to do that with the importer currently. I think that would be a trivial change though.

**Comment by MartinBischoff** [comment]
I just opened a pull request where the orientation of the mesh is maintained in Unity's coordinate system. See https://github.com/karl-/pb_Stl/pull/8/files
